apiVersion: v1
kind: Service
metadata:
  name: wayabank-admin-panel
  labels:
    app: wayabank-admin-panel
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: wayabank-admin-panel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayabank-admin-panel
  labels:
    app: wayabank-admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayabank-admin-panel
  template:
    metadata:
      labels:
        app: wayabank-admin-panel
    spec:
      containers:
        - name: wayabank-admin-panel
          image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/wayabank-admin-panel:imgtag
          env:
          - name: MESSAGING_GROUP_ID
            value: 'events'
          ports:
          - name: http
            containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/description
                operator: In
                values:
                - cfgprofile
                - wayabank-cfgprofile
